# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9ec0aa56-0154-42a5-bee8-b4c0b457eb5b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9ec0aa56-0154-42a5-bee8-b4c0b457eb5b".device = "/dev/disk/by-uuid/9ec0aa56-0154-42a5-bee8-b4c0b457eb5b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7303-21CF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8e780eeb-341a-407b-a9a2-6daf0e66401e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
